### ISSUE TITLE
Ignition MSSQL build: No such file or directory

### ISSUE THREAD

**Issue by patstave** [thirdgen88/ignition-examples#1]
I get the following build error when composing. Are some files missing?

> Attaching to my-ignition, ignition-mssql_db_1
my-ignition | /usr/local/bin/docker-entrypoint.sh: line 288: /usr/local/share/ignition/data/.docker-init-complete: No such file or directory
my-ignition exited with code 1
db_1       | 2019-08-05 13:11:24.20 Server      Microsoft SQL Server 2017 (RTM-CU15) (KB4498951) - 14.0.3162.1 (X64)
db_1    May 15 2019 19:14:30
db_1    Copyright (C) 2017 Microsoft Corporation
db_1    Developer Edition (64-bit) on Linux (Ubuntu 16.04.6 LTS)

docker-compose.yml is attached:
[docker-compose.yml.txt](https://github.com/thirdgen88/ignition-examples/files/3467876/docker-compose.yml.txt)

**Comment by rssw** [comment]
A little late, but I had the same issue and just wanted to leave the resolution for others:

The problem is that changing from a volume to a mount is not exactly the same.  A volume will initialize with all the files from the mount point in the container, whereas a mount will overwrite the mount point in the container, making all the files at the original mount point inacessible.  In order to use a mount point on the host like this, it will be neccesary to either first copy all the files from the container to the host directory to be mounted, or to use the following in the compose.yaml:
# inside a docker-compose file
```
  ...
  volumes:
    bind-test:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/user/test
```
Reference: 
 https://docs.docker.com/storage/volumes/
 https://stackoverflow.com/questions/42848279/how-to-mount-volume-from-container-to-host-in-docker

**Comment by thirdgen88** [comment]
Closing this one out due to inactivity and since we have a posted solution.  Thanks @rssw for posting a solution; using the longer-form syntax for the volume mount is the key to having Docker Engine pre-populate the empty [new] volume location with files from the container image prior to startup.

I'm working on an alternative method of gateway state preservation (for other container engines/services that don't behave that way and always stomp [with an empty folder] the chosen volume target) that should be coming soon.
