### ISSUE TITLE
Setting gateway system name and admin username in yml file

### ISSUE THREAD

**Issue by iamthebull** [thirdgen88/ignition-examples#5]
I am trying to set the gateway system name and the gateway admin username. In the yml file I have:
```version: '3.1'
services:
  gateway:
    image: kcollins/ignition:8.1.1  # You can change `latest` to a specific version, e.g. `8.0.5`
    ports:
      - "8088:8088"
    stop_grace_period: 30s
    secrets:
      - gateway-password
    volumes:
      # - ./gateway_backup.gwbk:/restore.gwbk
      - gateway_data:/var/lib/ignition/data
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      GATEWAY_SYSTEM_NAME: DockerGW
      GATEWAY_ADMIN_USERNAME: david
      GATEWAY_ADMIN_PASSWORD_FILE: /run/secrets/gateway-password
      GATEWAY_SKIP_COMMISSIONING: 1
```
Is that the correct way to do it? It doesn't seem to be working. The skip commissioning seems to work though.

**Comment by thirdgen88** [comment]
I'm hoping that the naming of that new optional environment variable isn't confusing.  `GATEWAY_SKIP_COMMISSIONING` will, when set to `1`, skip the _automatic_ commissioning of the gateway.  So in essence, supplying the `GATEWAY_ADMIN_USERNAME` and `GATEWAY_ADMIN_PASSWORD` is superfluous when skipping auto-commissioning, since you'll be prompted for it by the gateway.  I'm pretty sure that the gateway name will still be set properly per the `GATEWAY_SYSTEM_NAME` declaration, once you go through the commissioning process.  Let me know if this helps...

**Comment by iamthebull** [comment]
Nah, it makes perfect sense. I was just trying to skip the Enable Quick Start prompt and it didn't clue in at the time that I was shooting myself in the foot by enabling GATEWAY_SKIP_COMMISSIONING. Do you have an option to stop the Enable Quick Start only?

**Comment by thirdgen88** [comment]
Good deal..  No, I took a look at that but it is a bit of a moving target right now with Quick Start still very new.  Look for that in the future though, it is definitely something I'd like to be able to customize in a fresh container startup..
